name: Yandex Tracker Release

on:
  push:
    branches:    
      - 'releases/**'
    tags:        
      - v*.*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      env:
        OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
        ORG_ID: ${{ secrets.ORG_ID }}
      run: |
        npm install
        node ./runRelease.js
